-- ============================================================================
--  cian — 設定ファイル（日本語版）
-- ============================================================================
--
--  以下はすべてコメントアウトされています。行頭の "-- " を消せば、その設定が
--  有効になります。何も外さなければ、cian は既定値で動きます。
--
--  このファイルの置き場所:
--    Linux / macOS : ~/.config/cian/init.lua
--    Windows       : %USERPROFILE%\.config\cian\init.lua
--                    （例: C:\Users\you\.config\cian\init.lua）
--    もしくは $CIAN_CONFIG_DIR を設定すれば、cian は
--    $CIAN_CONFIG_DIR/init.lua を読みます。
--
--  ※ このファイル自体は英語版 examples/init.lua の日本語訳です。中身のコードは
--     同じなので、好きな方をコピーして使ってください。
--
--  init.lua をすっきり保つ：SSH ホストとキーバインドは、それぞれ隣の別ファイル
--  （ssh.lua / keymap.lua、examples/ を参照）に分けられます。cian は init.lua の
--  直後に同じ設定として読み込むので、`cian.ssh{…}` / `cian.set_keymap(…)` は
--  そこでもここと同じように効きます。これで init.lua を「画面表示・Git/SVN・AI」
--  に集中させられます。読み込まれているファイルは `:where` で確認できます。
--
--  中身は素の Lua 5.4 です。変数・関数・`if` を自由に使えます（例: マシンごとに
--  別のシェルを指定するなど）。書き間違えても致命的にはならず、cian は起動時に
--  まとめて通知するだけで、そのまま動きます。
--
--  キー一覧はいつでも、アプリ内で `?`、`:man`、または `cian -man` で見られます。
-- ============================================================================


-- ----------------------------------------------------------------------------
--  テーマ
-- ----------------------------------------------------------------------------
-- 名前付きプリセットから始められます。内蔵プリセット:
--   "default" / "dark"        （内蔵のダークテーマ。既定値）
--   "solarized-light"         （別名 "solarized"）、"solarized-dark"
--   "dracula", "nord", "monokai", "one-dark", "tokyo-night"
--   "gruvbox-dark", "gruvbox-light"
--   "catppuccin-mocha"（別名 "catppuccin"）、"catppuccin-latte"
--   "github-light"
-- cian.set_theme "dracula"
--
-- 実行中にも切り替えられます（再起動不要）。`:theme` でギャラリーが開き、各
-- プリセットをライブでプレビューできます（Enter で決定、Esc で取消）。
-- `:theme <名前>` で直接指定も可。右クリックメニューからも開けます。
-- この方法で選んだテーマは記憶され（設定の隣の state.toml に保存。場所は
-- `:where` で確認）、次回起動時に再適用されます。上の cian.set_theme より優先
-- されるので、この行は実質「既定値」の指定になります。

-- …または個別の色を調整することもできます。値は "#rrggbb" か色名
-- （"yellow", "cyan" など）。指定しなかったキーは現在値を保ちます。プリセット
-- と上書きの併用も可能です:
-- cian.set_theme {
--   preset      = "solarized-light",  -- 起点にするプリセット（任意）
--   accent      = "#268bd2",  -- フォーカス枠・ハイライト・バーの色
--   status_bg   = "#eee8d5",  -- 下部ステータス行の背景
--   selected_bg = "#dcd5be",  -- 選択行のハイライト背景
--   visual_bg   = "#f7e4b0",  -- ビジュアル選択中のハイライト
--   mark_fg     = "#cb4b16",  -- マーク済みファイルの ● の色
-- }


-- ----------------------------------------------------------------------------
--  オプション  —  cian.set_option(name, value)
-- ----------------------------------------------------------------------------

-- パス引数なしで cian を起動したとき、両ペインが開くディレクトリ。既定では
-- デスクトップ、次にホームフォルダ。ショートカットから起動する場合など、作業
-- ディレクトリが exe の場所になってしまうときに便利です。
-- cian.set_option("home", "C:\\Users\\you\\Desktop")   -- Windows
-- cian.set_option("home", "~/Desktop")                 -- Linux / macOS（~ と $VAR は展開されます）

-- 埋め込みシェルパネルで動かすシェル。既定は $SHELL / %COMSPEC%。
-- cian.set_option("shell", "powershell.exe")
-- cian.set_option("shell", "pwsh.exe")     -- PowerShell 7
-- cian.set_option("shell", "/bin/zsh")

-- `y` でコピーしたとき、システムのクリップボードにもファイルを載せる（エクス
-- プローラー / Finder にも貼り付けられる）。既定: true。
-- cian.set_option("clipboard_on_copy", true)

-- SFTP のアップロード/ダウンロード後、リモートのファイルを読み直してローカルと
-- チェックサムを比較し、不一致なら警告する。既定: false（データをもう一度読む
-- ため、帯域より整合性が大事なときだけ有効に）。SFTP が必要（SCP フォールバック
-- は読み直せない）。
-- cian.set_option("verify_transfers", true)

-- 長い処理（コピー／移動／削除・圧縮・転送）が終わったら、端末のベルを鳴らし
-- デスクトップ通知（OSC 9）を出す。大きなコピーを走らせて席を外したときのため。
-- 既定: true。対応端末は Windows Terminal と iTerm2（非対応端末は無視します）。
-- cian.set_option("notify", false)
-- 通知が出るまでに処理が最低何秒かかっている必要があるか。既定: 5（短い処理は
-- 鳴りません）。
-- cian.set_option("notify_min_secs", 10)

-- 起動時にドットファイル（"." で始まる名前）を表示する。右クリックメニューで
-- ライブに切り替え可能。既定: true。
-- cian.set_option("show_hidden", true)

-- Nerd Font グリフ — ファイル種別アイコンや、ステータス行のブランチ／ディスク
-- 記号。既定 true。Nerd Font の入っていない端末では false にすると、それらの
-- グリフを出さなくなります（文字化け防止）。フォルダは色で識別できます。
-- cian.set_option("nerd_fonts", false)

-- 枠線の角: "rounded"（╭╮╯╰）か "plain"（直角）。未設定なら自動判定 —
-- 描画できる端末／フォントでは丸角、レガシー Windows コンソールでは直角。
-- 角がずれて見えるときは "plain" を強制してください。
-- cian.set_option("borders", "rounded")

-- ステータス行の上に出る、状況に応じたキーヒントバー。既定: true。キー操作が
-- 手に馴染んだら false にして画面をすっきりさせられます。
-- cian.set_option("key_hints", true)

-- インターフェースの言語（キー一覧、ステータス行、メニュー、ダイアログ）。
-- 既定: "en"（英語）。コメントを外すと日本語になります。
-- （右クリックメニューからライブに切り替えることもできます。）
-- cian.set_option("lang", "ja")

-- キー一覧（`?`）と右クリックメニューだけの言語。この 2 か所だけ `lang` を
-- 上書きします。インターフェースは英語のままメニュー／マニュアルだけ日本語で
-- 読む（またはその逆）のに便利。未設定なら `lang` に従います。
-- cian.set_option("menu_lang", "ja")

-- 分割 / ズーム / クローズのアニメーション時間（ミリ秒）。0 で全アニメーション
-- を無効化。既定は短くきびきびした遷移です。
-- cian.set_option("animation_ms", 120)
-- cian.set_option("animation_ms", 0)      -- 無効

-- F3 ビューアの `E` と `:edit` で使う外部エディタ。コマンドラインを指定し、末尾
-- にファイルパスが付きます。未設定なら $VISUAL / $EDITOR、次に PATH 上の
-- nvim → vim → vi の順で最初に見つかったものを使います（どれも無ければその旨
-- を表示）。
-- cian.set_option("editor", "nvim")
-- cian.set_option("editor", "code -w")   -- VS Code（タブを閉じるまで待機）


-- ----------------------------------------------------------------------------
--  キーバインド  —  cian.set_keymap("key", "action")
-- ----------------------------------------------------------------------------
-- `key` は 1 文字です。キーにアクションを割り当てると、ファイルペインでその
-- キーがアクションを起動します。使い方は 3 通り:
--
--   * キーを追加:  cian.set_keymap("x", "delete")   -- x でも削除できるように
--   * キーを変更:  既定のあるキーに割り当てると既定を置き換えます。
--                  `cian.set_keymap("d", "rename")` で `d` は削除ではなく
--                  リネームになります。
--   * キーを無効化: "none" に割り当てます。 cian.set_keymap("d", "none")
--
-- 以下は既定のバインドを、それを再現する行として並べたものです。既に有効なので
-- コメントアウトしてあります — 移動したい（"key" を変える）か、無効化したい
-- （"none"）ときだけコメントを外してください。構造キー（矢印、Enter、
-- Backspace、Tab、F キー、Ctrl-／Shift- の組み合わせ）は組み込みで、ここでは
-- 再割り当てできません。以下はすべて変更可能です。
--
--   -- 移動
--   cian.set_keymap("j", "cursor_down")
--   cian.set_keymap("k", "cursor_up")
--   cian.set_keymap("g", "cursor_top")      -- （`gg` コード。下の注記を参照）
--   cian.set_keymap("G", "cursor_bottom")
--   cian.set_keymap("D", "page_down")
--   cian.set_keymap("U", "page_up")
--   cian.set_keymap("l", "enter")           -- 選択中のディレクトリに入る
--   cian.set_keymap("-", "parent")          -- 親ディレクトリへ上がる
--
--   -- マーク / 選択
--   cian.set_keymap(" ", "mark_down")       -- スペース: マーク切替＋下へ
--   cian.set_keymap("v", "visual")          -- ビジュアル（範囲）選択モード
--   cian.set_keymap("V", "invert_marks")
--
--   -- ファイル操作
--   cian.set_keymap("c", "copy")            -- 反対ペインへコピー
--   cian.set_keymap("m", "move")            -- 反対ペインへ移動
--   cian.set_keymap("y", "paste")           -- ファイルクリップボードを貼り付け（= Ctrl+V）
--   -- Windows流のファイルクリップボードは Ctrl+C / Ctrl+X / Ctrl+V にも割当済み。
--   -- （再割当できるアクション名: copy, move, paste, cut, delete, …）
--   cian.set_keymap("d", "delete")          -- ゴミ箱へ
--   cian.set_keymap("r", "rename")
--   cian.set_keymap("a", "new_file")
--   cian.set_keymap("A", "new_dir")
--   cian.set_keymap("o", "sync_from_other") -- このペイン → 反対ペインのディレクトリ
--   cian.set_keymap("O", "sync_to_other")   -- 反対ペイン → このペインのディレクトリ
--   -- （反対ペインで開く操作は Ctrl+Enter にあります。文字キーが好みなら
--   --  ここで割り当ててください: cian.set_keymap("o", "open_other"))
--   cian.set_keymap("e", "open_external")   -- ファイルを OS の関連付けで開く
--
--   -- クリップボード
--   cian.set_keymap("p", "copy_path")       -- パス文字列をコピー
--   cian.set_keymap("P", "copy_file_ref")   -- ファイル参照をコピー（Finder/エクスプローラー）
--
--   -- 検索 / 絞り込み / 並べ替え
--   cian.set_keymap("f", "search")          -- この一覧内を検索
--   cian.set_keymap("n", "search_next")
--   cian.set_keymap("N", "search_prev")
--   cian.set_keymap("/", "filter")          -- インクリメンタル絞り込み
--   cian.set_keymap("F", "find_recursive")  -- 名前でファイルを再帰検索
--   cian.set_keymap(",", "sort")            -- 並べ替え順のピッカーを開く
--   cian.set_keymap("z", "jump_path")       -- 入力したパスへジャンプ
--   cian.set_keymap("=", "diff")            -- 両ペインのファイルを比較
--
--   -- タブ、パネル、ツール
--   cian.set_keymap("t", "new_tab")
--   cian.set_keymap("w", "close_tab")
--   cian.set_keymap("h", "history")
--   cian.set_keymap("s", "shortcuts")       -- ブックマークメニュー
--   cian.set_keymap("M", "menu")            -- 右クリックのコンテキストメニュー
--                                           -- （端末が報告できる環境では
--                                           --  Shift+Enter でも開けます）
--   cian.set_keymap(":", "command")         -- : コマンドライン
--   cian.set_keymap("q", "quit")
--
-- アクション名の一覧（第 2 引数に使えるもの）:
--   移動     : cursor_down  cursor_up  cursor_top  cursor_bottom
--              page_down  page_up  parent  enter
--   マーク   : mark_down  mark_up  invert_marks  visual
--   ファイル : copy  move  paste  cut  delete  rename  new_file  new_dir
--              open_other  open_other_tab  open_external
--              sync_from_other  sync_to_other
--   クリップ : copy_path  copy_file_ref
--   検索     : search  search_next  search_prev  filter
--              find_recursive  grep_recursive  sort  jump_path  diff
--   パネル   : new_tab  close_tab  history  shortcuts  ssh  view  menu
--   その他   : refresh  manual  command  quit  none  （none はキーを無効化）
--
-- 注記: `cursor_top` は `gg` コード（g を 2 回）に割り当てられています。1 キー
-- では再現できない vim 由来の操作なので、ここに名前を挙げているのはマニュアルに
-- 載せるためだけです。`grep_recursive`（ファイル内容の検索）には既定の文字が
-- ありません。使いたいなら割り当ててください。例:
-- cian.set_keymap("G", "grep_recursive")。


-- ----------------------------------------------------------------------------
--  SSH ホスト  —  cian.ssh { ... }
-- ----------------------------------------------------------------------------
-- SSH ピッカー（右クリック → SSH 接続、またはシェル内から）と、ファイルの
-- アップロード／ダウンロードで使うホストを登録します。転送は SFTP を使い、
-- サーバに SFTP サブシステムが無ければ自動で古典的な SCP プロトコルに
-- フォールバックします。どちらで転送したかはステータス行に表示されます。
-- トップレベルの `users` は全ホスト共通の既定で、ホストごとに上書きできます。
-- user は名前だけの文字列か、パスワードを持たせたテーブル（cian が自動ログイン
-- するため）のどちらかです。
--
-- セキュリティ注意: ここに平文 `password` を書くと、このファイルに平文で保存
-- されます。可能なら `password_cmd` を使ってください。コマンドを実行してその
-- 標準出力を使うので、秘密情報は OS の資格情報ストアに置け、ディスクに
-- 残りません。
--
-- cian.ssh {
--   -- 自前の users を持たない全ホストに適用される既定:
--   users = { "root", "deploy" },
--
--   hosts = {
--     -- 最小形: ピッカー用の名前とアドレス。既定の users を使う。
--     { name = "web1", host = "10.0.1.11" },
--
--     -- 非標準ポート:
--     { name = "db1",  host = "10.0.2.31", port = 2222 },
--
--     -- ホストごとの users。1 つは自動ログイン用にパスワードを記載:
--     { name = "stage", host = "stage.example.com",
--       users = {
--         "readonly",                                    -- 都度入力、自動ログインなし
--         { name = "admin", password = "hunter2" },      -- 平文（非推奨）
--         { name = "ci",    password_cmd = "pass show ci/stage" },  -- ストアから取得
--       },
--     },
--
--     -- `notes` はサーバに関する事実（OS、ミドル、バージョン）を記録します。
--     -- ここにシェル接続すると、その内容が AI に伝わります（ai_context 参照）。
--     { name = "db1", host = "10.0.2.31",
--       notes = "RHEL 8.9; Oracle 19c; /u01 の空きが少ない" },
--   },
-- }


-- ----------------------------------------------------------------------------
--  AI  —  cian.ai { ... }   （任意。Python + Azure OpenAI アクセスが必要）
-- ----------------------------------------------------------------------------
-- cian の AI 機能（`:ai` チャット、後々のジャンク検出／構成提案など）を有効に
-- します。cian は同梱の小さな Python ヘルパー経由で Azure OpenAI と通信し、
-- crmaine と同じ Windows ブローカー（WAM）認証を使います。Python・パッケージ・
-- サインインのいずれかが使えなければ AI 機能は静かに無効化され、cian はこれまで
-- どおり動作します。このブロックが無ければ AI は完全にオフです。
--
-- ヘルパーには次の Python パッケージが必要です: `openai`、ブローカー認証用に
-- `azure-identity-broker`（サインインダイアログの親ウィンドウ用に `pywin32`）。
-- モデルに送るのは各機能が必要とする分だけ（ファイル名とサイズ。ファイル内容は
-- 機能が明示的に要求する場合のみ）です。
--
-- エンドポイントは既定では空です。組織の API ゲートウェイのアドレスは、
-- 公開リポジトリのソースではなく、その組織の init.lua に書くべきものなので。
-- 未設定のまま AI 機能を使うと、何を設定すればよいかを表示して止まります。
--
-- 設定例:
-- cian.ai {
--   endpoint    = "https://your-apim.azure-api.net/llmaoai",  -- Azure OpenAI / APIM
--   model       = "gpt-5-mini",
--   auth_mode   = "broker",    -- "broker"（Windows AAD）、"apikey"、"mock"（オフラインのエコー）
--   -- python   = "python",    -- 使うインタプリタ（既定: "python"）
--   -- api_version  = "2025-04-01-preview",
--   -- api_key      = "...",   -- auth_mode = "apikey" のときだけ
--   -- api_base_url = "http://localhost:11434/v1",  -- Ollama / LM Studio（OpenAI 互換）
-- }
--
-- 404「Resource not found」が出る? ブローカー／Azure 認証では `model` は
-- デプロイ名であり、リクエスト URL に入ります
-- （…/openai/deployments/<model>/chat/…）。ここが違うと 404 になります —
-- 動作しているクライアントに合わせて `model`（と `api_version`）を設定して
-- ください。もしゲートウェイが OpenAI 互換（model をボディに入れて
-- /chat/completions を叩く形式で、/openai/deployments/ パスではない）なら、
-- `api_base_url` にゲートウェイのベースを設定すれば、cian はブローカートークンで
-- そのルートを使います:
-- cian.ai {
--   auth_mode    = "broker",
--   api_base_url = "https://your-apim.azure-api.net/llmaoai",  -- OpenAI 互換ルート
--   model        = "<あなたのモデル>",
-- }
--
-- crmaine 連携 — cian.crmaine{}   （任意。VS Code の crmaine 拡張が必要）
-- VS Code で crmaine を起動するとローカルサーバが立ち、RAG インデックスが構築
-- されます。cian はその「起動済みサーバ」にアタッチして、同じインデックスに質問
-- できます（`:rag <質問>`）。使い方：まず VS Code で crmaine を起動 → 次に cian。
-- ポートはログインユーザ名から自動計算、cacheDir/endpoint/model は VS Code の
-- settings.json（crmaine.*）から都度読み込むので、通常は空の {} だけで動きます。
-- cian.crmaine{}
-- 上書きしたいときだけ指定:
-- cian.crmaine{
--   settings_path = [[C:\Users\<you>\AppData\Roaming\Code\User\settings.json]],
--   cache_dir     = [[<crmaine.cacheDir と同じ>]],  -- 通常は自動
--   port          = 6800,                            -- 通常は自動計算
-- }
-- 使えるコマンド:
--   :rag <質問>    RAG に質問（回答はストリーミング表示）
--   :agent <質問>  エージェント回答（ツール実行の進捗も表示）
--   :raginfo       診断（ポート・接続可否・使用中インデックス）
--   :index [パス]  指定フォルダ（省略時は今のペイン）を cian 専用インデックスに
--                  構築し、以後 :rag / :agent はそのインデックスだけで回答。
--                  crmaine 既存のインデックスには触れません。
--   :ragshared     :index をやめ、crmaine 本体のインデックスに戻す。
--   :impact <変更> その変更が影響する文書を分析（ストリーミング）。
--   :contradiction <トピック>  コーパス内の矛盾する記述を検出。
--   :glossary      インデックス済みコーパスの用語集を生成。
--   :searchfiles <語>  コーパスをキーワード検索し、該当ファイルをペインに一覧表示。
--   :coding [質問] 現在のファイル（F3で開いたもの、なければカーソル上）のコードを
--                  コンテキストに crmaine Ajent へ相談。F3ビューアでは A キーでも起動。
--
-- 前提知識 — cian.ai_context(...)
-- あなたの環境について AI が前提としてよいことを伝え、回答を一般論ではなく環境に
-- 即したものにします。すべての AI プロンプト（チャット、「直前のエラーを説明」、
-- コマンド提案 など）の先頭に付加されます。文字列またはリストを渡せます。呼び
-- 出すたびに追加されます。サーバ個別の事実は、上のホストの `notes` に書くほうが
-- 適切です（そのホストにシェル接続したとき自動で追加されます）。
-- cian.ai_context("ファイルペインは macOS から RHEL 8 の NFS マウントを見ている。")
-- cian.ai_context{
--   "本番は RHEL 8 + Oracle 19c + nginx 1.24 にデプロイする。",
--   "POSIX sh を優先。サーバでは bash 固有機能を有効にしていない。",
-- }
--
-- オンプレのエンタープライズ現場（Windows 端末 → RHEL + AIX、Oracle、WebLogic、
-- HULFT、JP1）向けの、より充実した実例です。合うものをコピーして自由に編集して
-- ください。文字列は何語でも構いませんが、日本語で書くとモデルも日本語で答え
-- やすくなります。使うにはコメントを外してください:
-- cian.ai_context{
--   -- 端末・母艦
--   "cian は Windows 10 + Windows Terminal 上で動かしている。ローカル側のパスやコマンドは Windows 前提（PowerShell / cmd）で考える。",
--   "回答は日本語でお願いします。",
--
--   -- 接続先サーバ
--   "シェルからは SSH で社内サーバに入る。AP サーバは RHEL、それ以外（バッチ／DB／運用管理）はすべて AIX。",
--   "AIX では GNU 拡張が使えないことが多い。ps / df / awk / sed 等は AIX(POSIX) の書式で提案し、GNU 固有オプション（--long-opts, sed -i など）は避けるか代替を併記する。",
--   "主要ミドルは Oracle 19c（移行途上で 11g も稼働）、WebLogic、Java 1.8、HULFT、JP1。",
--
--   -- 環境構成
--   "開発 / 検証 / 本番の 3 面構成。検証・本番は Act/Stb の冗長構成（AP サーバのみ両稼働）。",
--   "本番および待機系(Stb)での操作は特に慎重に。系切替やクラスタ・レプリケーションに影響し得る操作は、必ず確認を取ってから。",
--
--   -- サーバの役割
--   "AP サーバ(RHEL) = API / Web 画面の提供。バッチサーバ(AIX) = バッチ処理と HULFT でのデータ授受。DB サーバ(AIX) = Oracle（現行 11g、19c へ移行計画中）。運用管理サーバ(AIX) = JP1 でバッチをスケジューリング。",
--
--   -- シェルの流儀
--   "接続先では bash 拡張を使ってよい。Oracle 操作は sqlplus を多用する。",
--
--   -- 守ってほしいこと
--   "破壊的・不可逆なコマンド（rm, truncate, DROP / DELETE, 上書きリダイレクト, HULFT 送信, JP1 ジョブの強制終了など）は、実行を勧める前に必ず確認する。",
--   "推測で断定しない。確証がなければ「未確認」と明示し、確かめる手順を先に示す。",
--   "DB もファイルも巨大なことがある。まずサイズ・行数・容量と空きを確認し、余裕があることを確かめてから重い操作を勧める（巨大ファイルの cat、巨大ディレクトリの ls -R、SELECT * の全件取得、索引を使わないフルスキャン等を避ける）。パフォーマンスを意識した手順にする。",
--   "オフライン環境。AI 用の API 以外はインターネットに出られない。ダウンロード、パッケージ導入（pip / yum / dnf / wget / curl 取得）、外部リポジトリ参照を伴う手順は提案しない。すでにサーバにあるものだけで完結させる。",
-- }


-- ----------------------------------------------------------------------------
--  コマンドスニペット  —  cian.snippets { ... }   （任意）
-- ----------------------------------------------------------------------------
-- 何度も打つシェルコマンド（sqlplus ログイン、ログ tail、HULFT ジョブなど）の
-- ランチャーです。`:snip`（または右クリック「Snippets → shell」）で開き、入力で
-- 絞り込み、Enter でアクティブなシェルペインに送ります。
--
-- 開き方は Ctrl+Shift+Enter（シェルペインにフォーカスがあっても動きます）、
-- `:snip`、または右クリック「Snippets → shell」（メニュー上部）です。
--
-- 各エントリ: `cmd`（必須、送るテキスト）、`name`（ラベル。既定は cmd）、
-- `enter`（既定 true = 即実行。false = 確認用に入力だけ）、`confirm`（既定
-- false = すぐ送る。true = 先に確認 — 破壊的なものに使う）。呼び出すたびに追加
-- されます。
--
-- `cmd` には複数コマンドを入れられます — 各行に 1 つずつ書き（Lua の `[[ ]]`
-- 文字列が最もきれい）、enter = true なら順番に実行されます。
--
-- オンプレの Oracle / HULFT / JP1 現場向けの実例です。合うものをコピーして
-- ください。
-- cian.snippets{
--   -- ── 参照系（安全なので enter=true で即実行）──────────────────────
--   { name = "df 空き確認",        cmd = "df -g" },            -- AIX は df -g（RHEL は df -h）
--   { name = "ディスク使用 top",   cmd = "du -sh * | sort -rh | head" },
--   { name = "アプリログ tail",    cmd = "tail -f /var/log/app/app.log" },
--   { name = "プロセス確認 (java)", cmd = "ps -ef | grep -i java | grep -v grep" },
--   { name = "自分のジョブ",        cmd = "ps -fu $LOGNAME" },
--
--   -- ── まとめて流す（複数行。cd してから中身を確認）────────────────
--   { name = "配置先を確認", cmd = [[
-- cd /app/deploy/current
-- pwd
-- ls -ltr *]] },
--
--   -- ── 接続系（enter=false で接続先を目視してから Enter）───────────
--   { name = "sqlplus 開発19c",  cmd = "sqlplus app@DEV19C",  enter = false },
--   { name = "sqlplus 検証11g",  cmd = "sqlplus app@STG11G",  enter = false },
--   { name = "WebLogic 環境",     cmd = ". /app/wls/setDomainEnv.sh", enter = false },
--
--   -- ── 状態照会（HULFT / JP1）──────────────────────────────────────
--   { name = "HULFT 配信状況",   cmd = "utllist -o d" },
--   { name = "JP1 ジョブ状態",   cmd = "jpqjobget -F AJSROOT1 -l" },
--
--   -- ── 副作用あり（confirm=true で送信前に確認）───────────────────
--   { name = "HULFT 送信 定型",  cmd = "utlsend -f SENDID -sync", confirm = true },
--   { name = "AP 再起動",         cmd = "/app/bin/restart.sh", confirm = true },
-- }


-- ----------------------------------------------------------------------------
--  オープンハンドラ & ヘルパー
-- ----------------------------------------------------------------------------
-- 指定した拡張子に対して Enter（または `open_external`）が何をするかを決めます。
-- ハンドラにはフルパスが渡されます。プログラムをデタッチして起動するには
-- cian.spawn を、OS の既定の関連付けに渡すには cian.open を使います。
--
-- cian.on_open("md", function(path)
--   cian.spawn { "code", path }          -- Markdown を VS Code で開く
-- end)
--
-- cian.on_open("png", function(path)
--   cian.open(path)                      -- 画像ビューアは OS に選ばせる
-- end)
--
-- cian.on_open("csv", function(path)
--   cian.spawn { "nvim", path }
-- end)


-- ----------------------------------------------------------------------------
--  ショートカット（ブックマーク）について
-- ----------------------------------------------------------------------------
-- ブックマーク（`s` メニュー）はアプリ内で管理します — そこで `a` を押すか、
-- 履歴一覧でパスの上で `a` を押します — そしてこのファイルの隣の shortcuts.lua
-- に保存されます。ここで設定することは何もありません。
--
-- メニューは階層式です: `A`（Shift+a）で今いる階層にフォルダを作り、Enter / →
-- でフォルダに入り、Esc / ← で戻ります。入れ子の例は
-- examples/shortcuts.lua を参照してください（ターゲットはパス、URL、アプリの
-- いずれでもよく、フォルダは好きなだけ深くできます）。
