-- ============================================================================
--  cian — configuration
-- ============================================================================
--
--  Everything below is COMMENTED OUT. Delete the leading "-- " on any line to
--  turn that setting on. With nothing uncommented, cian runs on its defaults.
--
--  Where this file goes:
--    Linux / macOS : ~/.config/cian/init.lua
--    Windows       : %USERPROFILE%\.config\cian\init.lua
--                    (e.g. C:\Users\you\.config\cian\init.lua)
--    Or set $CIAN_CONFIG_DIR to point somewhere else; cian reads
--    $CIAN_CONFIG_DIR/init.lua then.
--
--  It is plain Lua 5.4, so you can use variables, functions and `if` around
--  any of this (e.g. a different shell per machine). Mistakes are never fatal:
--  cian collects them and shows a notice on startup instead of refusing to run.
--
--  See the full key list any time with `?` in the app, `:man`, or `cian -man`.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  THEME
-- ----------------------------------------------------------------------------
-- Start from a named preset. Built in: "solarized-light" (aka "solarized"),
-- and "default" / "dark" (the built-in dark theme, which is the default).
-- cian.set_theme "solarized-light"

-- …or tune individual colors. Values are "#rrggbb" or a color name
-- ("yellow", "cyan", …). Any key you leave out keeps its current value, and a
-- preset can be combined with overrides:
-- cian.set_theme {
--   preset      = "solarized-light",  -- optional base to start from
--   accent      = "#268bd2",  -- focused borders, highlights, the bar
--   status_bg   = "#eee8d5",  -- background of the bottom status line
--   selected_bg = "#dcd5be",  -- highlight behind the selected row
--   visual_bg   = "#f7e4b0",  -- highlight while marking in visual mode
--   mark_fg     = "#cb4b16",  -- color of the ● on marked files
-- }


-- ----------------------------------------------------------------------------
--  OPTIONS  —  cian.set_option(name, value)
-- ----------------------------------------------------------------------------

-- The directory both panes open in when cian is started with no path argument.
-- Defaults to the Desktop, then your home folder. Handy when launched from a
-- shortcut, where the working directory would otherwise be wherever the exe is.
-- cian.set_option("home", "C:\\Users\\you\\Desktop")   -- Windows
-- cian.set_option("home", "~/Desktop")                 -- Linux / macOS (~ and $VARS expand)

-- Which shell runs in the embedded shell panel. Defaults to $SHELL / %COMSPEC%.
-- cian.set_option("shell", "powershell.exe")
-- cian.set_option("shell", "pwsh.exe")     -- PowerShell 7
-- cian.set_option("shell", "/bin/zsh")

-- Also put files on the SYSTEM clipboard when you copy with `y` (so they paste
-- in Explorer / Finder too). Default: true.
-- cian.set_option("clipboard_on_copy", true)

-- Show dotfiles (names starting with ".") on startup. Toggle live with the
-- right-click menu. Default: true.
-- cian.set_option("show_hidden", true)

-- Border corners: "rounded" (╭╮╯╰) or "plain" (square). Unset auto-picks —
-- rounded where the terminal/font can render them, square in the legacy
-- Windows console. Force "plain" if the corners look misaligned.
-- cian.set_option("borders", "rounded")

-- The contextual key-hint bar above the status line. Default: true. Set false
-- for a cleaner screen once the keys are muscle memory.
-- cian.set_option("key_hints", true)

-- Interface language (the key manual, status line, menus, dialogs).
-- Default: "en" (English). Uncomment to switch it to Japanese.
-- (You can also toggle live from the right-click menu.)
-- cian.set_option("lang", "ja")

-- Split / zoom / close animation length, in milliseconds. 0 disables all
-- animation. Default is a short, snappy transition.
-- cian.set_option("animation_ms", 120)
-- cian.set_option("animation_ms", 0)      -- off


-- ----------------------------------------------------------------------------
--  KEY BINDINGS  —  cian.set_keymap("key", "action")
-- ----------------------------------------------------------------------------
-- `key` is one character. Binding a key to an action makes that key trigger it
-- in the file panes. This works two ways:
--
--   * ADD a key:      cian.set_keymap("x", "delete")   -- x now deletes too
--   * CHANGE a key:   binding a key that already has a default REPLACES the
--                     default. `cian.set_keymap("d", "rename")` makes `d`
--                     rename instead of delete.
--   * DISABLE a key:  bind it to "none".  cian.set_keymap("d", "none")
--
-- The DEFAULT bindings are listed below, each as the line that would recreate
-- it. They are commented out because they are already active — uncomment one
-- only to move it (change the "key") or turn it off ("none"). Structural keys
-- (arrows, Enter, Backspace, Tab, the F-keys, and Ctrl-/Shift- combos) are
-- built in and not remappable here; everything below is.
--
--   -- Movement
--   cian.set_keymap("j", "cursor_down")
--   cian.set_keymap("k", "cursor_up")
--   cian.set_keymap("g", "cursor_top")      -- (the `gg` chord; see note)
--   cian.set_keymap("G", "cursor_bottom")
--   cian.set_keymap("D", "page_down")
--   cian.set_keymap("U", "page_up")
--   cian.set_keymap("l", "enter")           -- enter the highlighted directory
--   cian.set_keymap("-", "parent")          -- go up to the parent directory
--
--   -- Marking / selection
--   cian.set_keymap(" ", "mark_down")       -- space: toggle mark, move down
--   cian.set_keymap("v", "visual")          -- visual (range) select mode
--   cian.set_keymap("V", "invert_marks")
--
--   -- File operations
--   cian.set_keymap("y", "copy")            -- (c is a second default for copy)
--   cian.set_keymap("m", "move")
--   cian.set_keymap("d", "delete")          -- to the trash
--   cian.set_keymap("r", "rename")
--   cian.set_keymap("a", "new_file")
--   cian.set_keymap("A", "new_dir")
--   cian.set_keymap("o", "open_other")      -- open into the opposite pane
--   cian.set_keymap("O", "open_other_tab")  -- …in a new tab there
--   cian.set_keymap("e", "open_external")   -- hand the file to the OS opener
--
--   -- Clipboard
--   cian.set_keymap("p", "copy_path")       -- copy path text
--   cian.set_keymap("P", "copy_file_ref")   -- copy a file reference (Finder/Explorer)
--
--   -- Find / filter / sort
--   cian.set_keymap("f", "search")          -- search within this listing
--   cian.set_keymap("n", "search_next")
--   cian.set_keymap("N", "search_prev")
--   cian.set_keymap("/", "filter")          -- incremental filter
--   cian.set_keymap("F", "find_recursive")  -- find files by name, recursively
--   cian.set_keymap(",", "sort")            -- open the sort-order picker
--   cian.set_keymap("z", "jump_path")       -- jump to a typed path
--   cian.set_keymap("=", "diff")            -- diff the two panes' files
--
--   -- Tabs, panels, tools
--   cian.set_keymap("t", "new_tab")
--   cian.set_keymap("w", "close_tab")
--   cian.set_keymap("h", "history")
--   cian.set_keymap("s", "shortcuts")       -- the bookmarks menu
--   cian.set_keymap(":", "command")         -- the : command line
--   cian.set_keymap("q", "quit")
--
-- The full list of action names (for the second argument):
--   Movement : cursor_down  cursor_up  cursor_top  cursor_bottom
--              page_down  page_up  parent  enter
--   Marking  : mark_down  mark_up  invert_marks  visual
--   Files    : copy  move  delete  rename  new_file  new_dir
--              open_other  open_other_tab  open_external
--   Clipboard: copy_path  copy_file_ref
--   Find     : search  search_next  search_prev  filter
--              find_recursive  grep_recursive  sort  jump_path  diff
--   Panels   : new_tab  close_tab  history  shortcuts  ssh  view  menu
--   Misc     : refresh  manual  command  quit  none  (none disables the key)
--
-- Note: `cursor_top` is bound to the `gg` chord (press g twice), a vim-ism
-- that a single key cannot reproduce; naming it here is only so it appears in
-- the manual. `grep_recursive` (search file contents) has no default letter —
-- bind one if you want it, e.g. cian.set_keymap("G", "grep_recursive").


-- ----------------------------------------------------------------------------
--  SSH HOSTS  —  cian.ssh { ... }
-- ----------------------------------------------------------------------------
-- Populates the SSH picker (right-click → SSH connect, or in the shell) and the
-- file upload/download flow. Transfers use SFTP, falling back to the classic
-- SCP protocol automatically when the server has no SFTP subsystem; the status
-- line shows which one carried it. `users` at the top level is the fleet-wide default;
-- a host can override it. A user is either a bare name, or a table carrying its
-- password so cian can log in for you.
--
-- SECURITY NOTE: a plain `password` here is stored in clear text in this file.
-- Prefer `password_cmd`, which runs a command and uses its stdout — so the
-- secret lives in your OS credential store, not on disk.
--
-- cian.ssh {
--   -- Applied to every host that doesn't list its own users:
--   users = { "root", "deploy" },
--
--   hosts = {
--     -- Simplest: a name for the picker and an address. Uses the default users.
--     { name = "web1", host = "10.0.1.11" },
--
--     -- A non-standard port:
--     { name = "db1",  host = "10.0.2.31", port = 2222 },
--
--     -- Per-host users, one with a password typed in for auto-login:
--     { name = "stage", host = "stage.example.com",
--       users = {
--         "readonly",                                    -- prompts, no auto-login
--         { name = "admin", password = "hunter2" },      -- clear text (avoid)
--         { name = "ci",    password_cmd = "pass show ci/stage" },  -- from a store
--       },
--     },
--   },
-- }


-- ----------------------------------------------------------------------------
--  OPEN HANDLERS & HELPERS
-- ----------------------------------------------------------------------------
-- What Enter (or `open_external`) does for a given extension. The handler gets
-- the full path. Use cian.spawn to launch a program detached, or cian.open to
-- hand the path to the OS default opener.
--
-- cian.on_open("md", function(path)
--   cian.spawn { "code", path }          -- open Markdown in VS Code
-- end)
--
-- cian.on_open("png", function(path)
--   cian.open(path)                      -- let the OS pick the image viewer
-- end)
--
-- cian.on_open("csv", function(path)
--   cian.spawn { "nvim", path }
-- end)


-- ----------------------------------------------------------------------------
--  A note on shortcuts
-- ----------------------------------------------------------------------------
-- Bookmarks (the `s` menu) are managed inside the app — press `a` there, or `a`
-- on a path in the history list — and saved to shortcuts.yaml next to this file.
-- There is nothing to configure here for them.
