-- keymap.lua — キーバインド（init.lua から分離したもの）。
--
-- 任意。init.lua と同じディレクトリに置いてください。cian は init.lua の直後に
-- このファイルを「同じ設定」として読み込むので、ここに書いた
-- `cian.set_keymap(…)` は init.lua に書いたのと全く同じに効きます — init.lua を
-- 表示 / Git・SVN / AI まわりに集中させておくための分割です。
--
-- `key` は1文字。それをアクション名に割り当てます（一覧は examples/init.lua、
-- またはアプリ内で `?` / `:man`）。既に既定のあるキーに割り当てると、その既定を
-- 「置き換え」ます。"none" に割り当てるとそのキーを無効化します。
--
--   cian.set_keymap("x", "delete")          -- x でも削除できるように
--   cian.set_keymap("d", "rename")          -- d を削除ではなくリネームに
--   cian.set_keymap("d", "none")            -- d を無効化
--   cian.set_keymap("G", "grep_recursive")  -- grep には既定の文字がない
--
-- 既定のバインド（それを再現する1行として掲載）は examples/init.lua の
-- KEY BINDINGS にあります — 移動または無効化したいときだけ、そこから1行を
-- ここへコピーしてください。構造キー（矢印・Enter・Tab・Fキー・Ctrl/Shift の
-- 組み合わせ）は組み込みで、再割り当てはできません。
