-- keymap.lua — key bindings, split out of init.lua.
--
-- OPTIONAL. Put this file next to init.lua (same directory). cian loads it right
-- after init.lua into the SAME config, so `cian.set_keymap(…)` here works exactly
-- as it would in init.lua — it just keeps init.lua focused on display / Git-SVN /
-- AI.
--
-- `key` is one character; bind it to an action name (see the full list in
-- examples/init.lua, or `?` / `:man` in the app). Binding a key that already has
-- a default REPLACES it; bind to "none" to disable a key.
--
--   cian.set_keymap("x", "delete")       -- x now deletes too
--   cian.set_keymap("d", "rename")       -- make d rename instead of delete
--   cian.set_keymap("d", "none")         -- disable d
--   cian.set_keymap("G", "grep_recursive")  -- grep has no default letter
--
-- The defaults (each shown as the line that would recreate it) are listed in
-- examples/init.lua under KEY BINDINGS — copy one here only to move or disable
-- it. Structural keys (arrows, Enter, Tab, the F-keys, Ctrl/Shift combos) are
-- built in and not remappable.
