-- ssh.lua — SSH ホスト（init.lua から分離したもの）。
--
-- 任意。init.lua と同じディレクトリ（~/.config/cian/、またはポータブル構成なら
-- .exe の隣）に置いてください。cian は init.lua の直後にこのファイルを「同じ
-- 設定」として読み込むので、ここに書いた `cian.ssh{…}` は init.lua に書いたのと
-- 全く同じです — init.lua を表示 / Git・SVN / AI まわりに集中させておくための
-- 分割です。
--
-- セキュリティ注意: ここに素の `password` を書くと、init.lua と同じくディスク上に
-- 平文で残ります。可能なら `password_cmd`（その標準出力が使われるので、秘密は
-- OS の資格情報ストアに置けます）か、鍵認証を使ってください。このファイルが
-- パスワードを含み、かつ誰でも読める権限だと、cian は起動時に警告します —
-- `chmod 600 ssh.lua` で黙らせられます。
--
-- 各フィールドの詳しい説明は examples/init.lua を参照。

-- cian.ssh {
--   -- 自分の users を持たない全ホストに適用される既定:
--   users = { "root", "deploy" },
--
--   hosts = {
--     { name = "web1", host = "10.0.1.11" },
--     { name = "db1",  host = "10.0.2.31", port = 2222 },
--
--     { name = "stage", host = "stage.example.com",
--       users = {
--         "readonly",                                   -- 入力を促す（自動ログインなし）
--         { name = "admin", password = "hunter2" },     -- 平文（避けたい）
--         { name = "ci",    password_cmd = "pass show ci/stage" }, -- ストアから取得
--       },
--     },
--
--     -- `notes` は、このホストにログイン中のシェルで AI に渡されます。
--     { name = "db1", host = "10.0.2.31",
--       notes = "RHEL 8.9; Oracle 19c; /u01 の空きが少ない" },
--   },
-- }
